apiVersion: apps/v1
kind: Deployment
metadata:
  name: agnhost-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ""
  template:
    metadata:
      labels:
        app: ""
    spec:
      containers:
      - name: agnhost-container
        image: registry.k8s.io/e2e-test-images/agnhost:2.38
        ports: []
