apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-sync-role-binding
  namespace: argocd
subjects:
- kind: User
  name: alice
roleRef:
  kind: Role
  name: argocd-sync-role
  apiGroup: rbac.authorization.k8s.io

